### ISSUE TITLE
Compiling does not work on OrangePi PC Plus

### ISSUE THREAD

**Issue by dl1nux** [bassamanator/armbian-orangepi-how-to#2]
Hi and thanks for your short instructions.

I tried it on a Oriange Pi PC Plus, but at the ent of compilation I get some warnings and the GPIO commands do not work.

GPIO Utility
[Compile] gpio.c
[Compile] readall.c
gpio.c: In function ‘doUsbP’:
gpio.c:944:25: warning: unused parameter ‘argc’ [-Wunused-parameter]
  944 | static void doUsbP (int argc, char *argv [])
      |                     ~~~~^~~~
gpio.c:944:37: warning: unused parameter ‘argv’ [-Wunused-parameter]
  944 | static void doUsbP (int argc, char *argv [])
      |                               ~~~~~~^~~~~~~
readall.c:1616:13: warning: ‘piPlusReadall’ defined but not used [-Wunused-function]
 1616 | static void piPlusReadall (int model)
      |             ^~~~~~~~~~~~~
[Link]
[Install]
chown: warning: '.' should be ':': „root.root“

All Done.

NOTE: To compile programs with wiringPi, you need to add:
    -lwiringPi
  to your compile line(s) To use the Gertboard, MaxDetect, etc.
  code (the devLib), you need to also add:
    -lwiringPiDev
  to your compile line(s).

pi@orangepipcplus:~$ sudo gpio readall
wiringPiSetup: mmap (PWM) failed: Invalid argument
pi@orangepipcplus:~$

Any ideas?

**Comment by bassamanator** [comment]
So `wiringOP` was not installable, and you were going step by step?

**Comment by bassamanator** [comment]
These are the official instructions for the `Orange Pi PC Plus`, give them a try:

1. Delete wiringOP directory, `rm -rf ~/.wiringOP` (you might need to use `sudo` and to individually delete sub directories)
2. `cd ~`
3. `git clone https://github.com/orangepi-xunlong/wiringOP`
4.
```shell
cd ~/wiringOP
sudo ./build clean
sudo ./build
```

**Comment by dl1nux** [comment]
This also doesn't work actually. I think there are some open issues in the actual code:
https://github.com/orangepi-xunlong/wiringOP/issues/107
https://github.com/orangepi-xunlong/wiringOP/issues/103

Same error messages appear as before. I think I'll have to wait for a fix.

Regards

**Comment by bassamanator** [comment]
Oh that sucks. I'll add a note about this board on the README.
